new/library/books/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path

from books import views
app_name="books"
urlpatterns = [

    path('',views.home,name="home"),
    path('addbook', views.addbook, name="addbook"),
    path('addbook1', views.addbook1, name="addbook1"),
    path('viewbook',views.viewbook,name="viewbook"),
    path('fact',views.fact,name="fact"),
    path('bookdetail/<int:p>',views.bookdetail,name="bookdetail"),
    path('bookdelete/<int:p>',views.bookdelete,name="bookdelete"),
    path('bookedit/<int:p>',views.bookedit,name="bookedit"),
    path('search',views.search,name="search"),

]

new/library/library/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('books.urls')),
    path('students/',include('students.urls')),

]

if(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

new/library/students/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path


from students import views
app_name="students"
urlpatterns = [

    path('register', views.register, name="register"),
    path('login', views.user_login, name="login"),
    path('logout', views.user_logout, name="logout"),
]

new/library/books/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    title=models.CharField(max_length=20)
    author = models.CharField(max_length=20)
    price=models.IntegerField()
    pdf = models.FileField(upload_to="books/pdf")
    cover=models.ImageField(upload_to="books/cover",null=True,blank=True)
    def __str__(self):
        return self.title

new/library/students/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class CustomUser(AbstractUser):
    phone=models.IntegerField(default=0)
    place= models.TextField(default="")
    def __str__(self):
        return self.username

new/library/books/forms.py
#Form definition

from django import forms
from books.models import Book
class Bookform(forms.ModelForm):
    class Meta:

        model=Book
        fields="__all__"

new/library/books/views.py
from django.shortcuts import render
from books.models import Book
from books.forms import Bookform
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

def home(request):
    # return HttpResponse("Welcome")
      return render(request,'home.html',)

@login_required
def bookdetail(request,p):
    b=Book.objects.get(id=p)

    return render(request,'book.html',{'b':b})

@login_required
def bookdelete(request,p):
    b=Book.objects.get(id=p)
    b.delete()
    return viewbook(request)

@login_required
def bookedit(request,p):
    b = Book.objects.get(id=p)
    if (request.method == "POST"):  # after submission
        form = Bookform(request.POST,request.FILES,instance=p)  # Creates form object initialised with values inside request.POST
        if form.is_valid():
            form.save()  # saves the form object inside Db table
        return viewbook(request)

    form=Bookform(instance=b)  #retrieved data will be filled
    return render(request,'edit.html',{'form':form})

# def addbook(request):
#     # return HttpResponse("Welcome")
#       return render(request,'addbook.html',)

@login_required
def search(request):
    query=""
    b=None
    if(request.method=="POST"):
        query=request.POST['q']
        if(query):
            b=Book.objects.filter(Q(title__icontains=query) | Q(author__icontains=query))
    return render(request,'search.html',{'query':query,'b':b})

@login_required
def addbook(request):
    if(request.method  =="POST"):
        t = request.POST['t']
        a = request.POST['a']
        p = request.POST['p']
        f = request.FILES['f']
        i = request.FILES['i']
        b = Book.objects.create(title=t, author=a, price=p, pdf=f, cover=i)
        b.save()
        return viewbook(request)
    return render(request,'addbook.html')

@login_required
def addbook1(request):
    if(request.method=="POST"):  #after submission
        form=Bookform(request.POST) #Creates form object initialised with values inside request.POST
        if form.is_valid():
            form.save() #saves the form object inside Db table
        return viewbook(request)
    form=Bookform()   #empty form object with no values
    return render(request, 'addbook1.html',{'form':form})

@login_required
def viewbook(request):
    # return HttpResponse("Welcome")
    k=Book.objects.all()
    return render(request,'viewbook.html',{'b':k})


@login_required
def fact(request):
    if (request.method =="POST"):
        num =int(request.POST['n'])
        f=1
        for i in range(1,num+1):
            f=f*i
        return render(request, 'fact.html',{'fact':f})
    return render(request, 'fact.html')

new/library/students/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required

def register(request):
    if (request.method == "POST"):
        u = request.POST['u']
        p = request.POST['p']
        cp = request.POST['cp']
        fname = request.POST['x']
        lname = request.POST['y']
        e = request.POST['e']
        ph = request.POST['ph']
        pl = request.POST['pl']

        if (p == cp):
            u = CustomUser.objects.create_user(username=u, password=p, first_name=fname, last_name=lname, email=e, phone=ph, place=pl)
            u.save()
            return redirect('books:home')
        else:
            return HttpResponse("Passwords are not same")
    return render(request,'register.html')

def user_login(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p = request.POST['p']
        user=authenticate(username=u,password=p)
        if user:
            login(request,user)
            return redirect('books:home')
        else:
            return HttpResponse("Invalid Credentials")
    return render(request,'login.html',)

@login_required
def user_logout(request):
    logout(request)
    return redirect('students:login')

new/library/templates/addbook.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<h3 class="mt-4">Add Book Details-User Defined</h3></center><br>


  <div class="mb-3">
    <label class="form-label">Title</label>
      <input type="text" class="form-control" name="t" placeholder="Title">
  </div><br>
  <div class="mb-3">
    <label class="form-label">Author</label>
      <input type="text" class="form-control" name="a" placeholder="Author">
  </div><br>
  <div class="mb-3">
    <label class="form-label">Price</label>
      <input type="text" class="form-control" name="p" placeholder="Price">
  </div><br><br>
  <div class="mb-3">
    <label class="form-label">PDF</label>
      <input type="file" class="form-control" name="f">
  </div><br>
  <div class="mb-3">
    <label class="form-label">Cover</label>
      <input type="file" class="form-control" name="i">
  </div><br>
  <center><button type="submit" class="form-control">Submit</button></center>
</form>
{% endblock %}

new/library/templates/addbook1.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% block title %}
Add
{% endblock %}
{% block content %}
<center>
<h3 class="mt-4">Add Book Details-Built in</h3></center>

<form method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit">
</form>
{% endblock %}

new/library/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>


<nav class="navbar navbar-expand-lg navbar-light bg-secondary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Library Apps</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'books:home' %}">Home</a>
        </li>
          {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'books:addbook' %}">Add Book</a>
        </li>

           <li class="nav-item">
          <a class="nav-link" href="{% url 'books:addbook1' %}">Add Books 1</a>
        </li>
            <li class="nav-item">
          <a class="nav-link" href="{% url 'books:viewbook' %}">View Book</a>
        </li>
           <li class="nav-item">
          <a class="nav-link" href="{% url 'books:fact' %}">Factorial of a number</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'students:logout' %}">logout</a>
        </li>
          {% else %}
          <li class="nav-item">
          <a class="nav-link" href="{% url 'students:register' %}">Register</a>
        </li>
           <li class="nav-item">
          <a class="nav-link" href="{% url 'students:login' %}">login</a>
        </li>
         {% endif %}


      </ul>
      <form class="d-flex" method="POST" action="{% url 'books:search' %}">
          {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

new/library/templates/book.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% block title %}
Add
{% endblock %}
{% block content %}
<center>
<h3 class="mt-4">Book Details</h3>
    <table class="table table-bordered" style="width:50%;">
    <tr>
        <th>ID</th>
        <td>{{b.id}}</td>
    </tr>
    <tr>
        <th>COVER</th>
        <td><img src="{{b.cover.url}}" height="100px" width="100px"></td>
    </tr>
    <tr>
        <th>TITLE</th>
        <td>{{b.title}}</td>
    </tr>
    <tr>
        <th>AUTHOR</th>
        <td>{{b.author}}</td>
    </tr>
    <tr>
        <th>PRICE</th>
        <td>{{b.price}}</td>
    </tr>
    <tr>
        <th>DOCUMENT</th>
        <td><a href="{{b.pdf.url}}">Download</a></td>
    </tr>
    </table>

</center>

{% endblock %}

new/library/templates/edit.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% block title %}
Add
{% endblock %}
{% block content %}
<center>
<h3 class="mt-4">Edit Book Details-Built in</h3></center>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
    {{form.as_table}}
        </table>
    <input type="submit">
</form>
{% endblock %}

new/library/templates/fact.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title %}
Add
{% endblock %}
{% block content %}
<center>
<h3 class="mt-4">Factorial of a number</h3>
<form method="POST">
    {% csrf_token %}
<div class="mb-3">
  <label  class="form-label">Number</label>
  <input type="number" class="form-control"  name="n" placeholder="Enter the number">
</div>

<div class="mb-3">

  <input type="submit" class="form-control">
</div>
    </form>
{% if fact %}
    <h4>Factorial is {{fact}}</h4>
    {% endif %}
    </center>

{% endblock %}

new/library/templates/home.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<h3 class="mt-4">Welcome to Home Page</h3>
{% if user.is_authenticated %}
    <p>{{user.username}}</p>
    {% else %}
    <p>Guest</p>
    {% endif %}
</center>
{% endblock %}

new/library/templates/login.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<h3 class="mt-4">Login</h3></center>
<form method="POST">
   {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Username</label>
      <input type="text" class="form-control" name="u" placeholder="Enter the username">
  </div><br>
  <div class="mb-3">
    <label class="form-label">Password</label>
      <input type="password" class="form-control" name="p" placeholder="Enter the password">
  </div><br>
<center><button type="submit" class="form-control">Submit</button></center>
</form>
</center>
{% endblock %}

new/library/templates/register.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<h3 class="mt-4">Register</h3></center><br>
<form method="POST">
   {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Username</label>
      <input type="text" class="form-control" name="u" placeholder="Enter the username">
  </div><br>
  <div class="mb-3">
    <label class="form-label">Password</label>
      <input type="password" class="form-control" name="p" placeholder="Enter the password">
  </div><br>
  <div class="mb-3">
    <label class="form-label">Confirm password</label>
      <input type="password" class="form-control" name="cp" placeholder="Enter the password">
  </div><br>
  <div class="mb-3">
    <label class="form-label">First name</label>
      <input type="text" class="form-control" name="x" placeholder="Enter the firstname">
  </div><br>
  <div class="mb-3">
    <label class="form-label">Last name</label>
      <input type="text" class="form-control" name="y" placeholder="Enter the lastname">
  </div><br>
  <div class="mb-3">
    <label class="form-label">Email</label>
      <input type="text" class="form-control" name="e" placeholder="Enter the email">
  </div><br>
  <div class="mb-3">
    <label class="form-label">Phone</label>
      <input type="number" class="form-control" name="ph" placeholder="Enter the phone number">
  </div><br>
  <div class="mb-3">
    <label class="form-label">Place</label>
      <input type="text" class="form-control" name="pl" placeholder="Enter the email">
  </div><br>
  <center><button type="submit" class="form-control">Submit</button></center>
</form>
{% endblock %}

new/library/templates/search.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
{% block title %}
Add
{% endblock %}
{% block content %}
<center>
<h3 class="mt-4">Book Details</h3>
    {% if b %}
    <table class="table table-bordered" style="width:50%;">
    <tr>
        <th>ID</th>
        <th>COVER</th>
        <th>TITLE</th>
        <th>AUTHOR</th>
        <th>PRICE</th>
        <th>DOCUMENT</th>
        <th>VIEW</th>
        <th>EDIT</th>
        <th>DELETE</th>
    </tr>
    {% for i in b %}
     <tr>
         <td>{{i.id}}</td>
         <td><img src="{{i.cover.url}}" height="100px" width="100px"></td>
         <td>{{i.title}}</td>
         <td>{{i.author}}</td>
         <td>{{i.price}}</td>
         <td><a href="{{i.pdf.url}}">Download</a></td>
         <td><a href="{% url 'books:bookdetail' i.id %} " class="btn btn-danger">View</a></td>
         <td><a href="{% url 'books:bookedit' i.id %}" class="btn btn-danger">Edit</a></td>
         <td><a href="{% url 'books:bookdelete' i.id %} " class="btn btn-danger">Delete</a></td>
    </tr>

    {% endfor %}
</table>
    {% else %}
    <h4>No Results Found</h4>
    {% endif %}
    </center>

{% endblock %}

new/library/templates/viewbook.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<h3 class="mt-4">Book List</h3>

<table class="table table-bordered" style="width:50%;">
    <tr>
        <th>ID</th>
        <th>COVER</th>
        <th>TITLE</th>
        <th>AUTHOR</th>
        <th>PRICE</th>
        <th>DOCUMENT</th>
        <th>VIEW</th>
        <th>EDIT</th>
        <th>DELETE</th>
    </tr>
    {% for i in b %}
     <tr>
         <td>{{i.id}}</td>
         <td><img src="{{i.cover.url}}" height="100px" width="100px"></td>
         <td>{{i.title}}</td>
         <td>{{i.author}}</td>
         <td>{{i.price}}</td>
         <td><a href="{{i.pdf.url}}">Download</a></td>
         <td><a href="{% url 'books:bookdetail' i.id %} " class="btn btn-danger">View</a></td>
         <td><a href="{% url 'books:bookedit' i.id %}" class="btn btn-danger">Edit</a></td>
         <td><a href="{% url 'books:bookdelete' i.id %} " class="btn btn-danger">Delete</a></td>
    </tr>

    {% endfor %}
</table>
    </center>
<!--<ol>-->
<!--    {% for i in b %}-->
<!--    <li>Book Details</li>-->
<!--    <ul>-->
<!--        <li>Title:{{i.title}}</li>-->
<!--        <li>Author:{{i.author}}</li>-->
<!--        <li>Price:{{i.price}}</li>-->
<!--    </ul>-->
<!--    {% endfor %}-->
<!--</ol>-->
{% endblock %}